### ISSUE TITLE
Hoping the code will be soon released

### ISSUE THREAD

**Issue by Yurri-hub** [cgtuebingen/SIGNeRF#1]

**Comment by JDihlmann** [comment]
Hey Yurri, first of all thanks for your interest in SIGNeRF. We are still polishing the code and waiting for responses of reviewers. So sadly we still need a bit of time, expect a code release at the end of february. If you need any comparative material for your research feel free to reach out via email and tell us the specifics you need.

**Comment by Yurri-hub** [comment]
> Hey Yurri, first of all thanks for your interest in SIGNeRF. We are still polishing the code and waiting for responses of reviewers. So sadly we still need a bit of time, expect a code release at the end of february. If you need any comparative material for your research feel free to reach out via email and tell us the specifics you need.

Thanks a lot for your reply. Wish a desired result with your paper.

**Comment by JDihlmann** [comment]
Sorry for the delay, the code is live now 😃
