### ISSUE TITLE
How to place a proxy object into the Nerf scene?

### ISSUE THREAD

**Issue by acmff22** [cgtuebingen/SIGNeRF#2]
Thanks for your great work, it's really enlightening.
In the object generation pipeline, how to place a proxy object into the Nerf scene and render the corresponding color, depth, and mask images?

**Comment by JDihlmann** [comment]
Thanks for your interest and the kind words. The proxy object is a mesh, we build a custom viewer for nerfstudio, that renders the mesh scene (rgb / depth) and the NeRF scene (rgb/depth) for the current camera perspective. We compare the rendered depth in image space which results in a mask for the visible parts of the proxy object. We then simply use the mask to combine both rgb images. As this runs very quick in the web with three js and the nerfstudio image renderer we can freely move the object within the three js scene and see the combined render in near real time and therefore precisely place the object. Does this answer your question?

**Comment by JDihlmann** [comment]
You can test it live now, and view how we do it in the `renderer.py` and `datasetgenerator.py`
