### ISSUE TITLE
Unable to load EGL Library

### ISSUE THREAD

**Issue by ravewater** [cgtuebingen/SIGNeRF#4]
Hi there, 
After installing the code using the instructions provided I now get a error  ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None) 
This happens whenever I try using a training command method in nerfstudio.
 
 I'm using windows 11, installing using conda, nerfstudio 1.0.2, pyhon 3.10.6,

**Comment by JDihlmann** [comment]
We use EGL for headless rendering of pyrender, you can try to deactivate it by deleting the line `os.environ['PYOPENGL_PLATFORM'] = 'egl'` in [signerf/renderer/renderer.py](https://github.com/cgtuebingen/SIGNeRF/blob/649da7f81ee5c96e2acd1bdcea2db37996b74742/signerf/renderer/renderer.py#L13). If this does not work please check your OpenGL installation. You can also find more information on the Offscreen Pyrender [here](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html), maybe you want to try osmesa as a setting. In general everything is tested on a Linux system, we recommend using WSL on windows.
