### ISSUE TITLE
connection: [WinError 10061] Unable to connect because the target computer actively refused it. '))

### ISSUE THREAD

**Issue by snowwhitewings** [cgtuebingen/SIGNeRF#5]
Hello, 
I have installed the code and set up the file structure according to the example. Execute command: 
ns-train signerf --data datasets/bear --output-dir ./outputs --experiment-name grizzly --pipeline.model.predict_normals True --load_dir outputs/bear/nerfacto/2024-03-21_164949/ nerfstudio_models --previous_experiment_dir generations/bunny. 
I got the error:
Could not connect to server, is the server reachable at http://127.0.0.1:5000:5000? HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /sdapi/v1/img2img (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A8D20BAA40>: Faile connection: [WinError 10061] Unable to connect because the target computer actively refused it. '))
How can i solve it. 
Thank you.

**Comment by JDihlmann** [comment]
Hey, did you install Stable Diffusion WebUI correctly as described [here](https://github.com/cgtuebingen/SIGNeRF/?tab=readme-ov-file#2-stable-diffusion-web-ui-setup)? After launching it with `bash webui.sh --port 5000 --no-half --xformers --api` it should be reachable under [http://127.0.0.1:5000](http://127.0.0.1:5000), is this site visible for you? If not your installation of SD WebUI is off, you can follow the steps [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui). If this site is visible for you my next question would be if you changed something in the code or in the config as the URL you posted has two times the port which is incorrect http://127.0.0.1:5000:5000/?... should be http://127.0.0.1:5000/?...
