### ISSUE TITLE
About inpainting difference between diffusers and stable diffusion webui

### ISSUE THREAD

**Issue by Yzhbuaa** [cgtuebingen/SIGNeRF#6]
Hello, I appreciate your impressive efforts. I'm curious as to why the Stable Diffusion WebUI is used in place of diffusers for the tasks of reference sheet generation and inpainting. Could you kindly clarify if there are any distinct differences between the two implementations? Many thanks in advance!

**Comment by JDihlmann** [comment]
Hey, good question we used WebUI at the beginning to quickly iterate over multiple settings that WebUI already provides (e.g. multi constrains depth+normal, masking options). Before WebUI we used [ControlNetInpaint](https://github.com/mikonvergence/ControlNetInpaint) but sadly only has SD 1.5 support. For the release of the work, rewriting for diffusers would have been to much of a time risk without benefit. But your probably right, for the code release we could have made a cleaner version with diffusers. At the end it wouldn't make much of a difference other than having cleaner code and a more narrow implementation (worse for people that like to experiment e.g. replacing the depth constrain with something different).

**Comment by Yzhbuaa** [comment]
Thank you for your thorough explanation! In an attempt to replicate the 'multi view consistent' results discussed in your paper, I've embarked on using sdxl-base-1.0 and depth controlnet alongside the StableDiffusionXLControlNetInpaintPipeline, a diffuser pipeline. Presently, I'm utilising a reference sheet of size 2 (configured as a 1x2 image grid) where the left image serves as the reference and the right is left blank for the 'Image Set Update'. However, the results obtained thus far have been disappointing, with the generated right part of the reference sheet appearing somewhat faded. 

I've identified three potential factors that could contribute to these suboptimal outcomes:

1. The size of the reference sheet may be insufficient, as a 2x3 configuration was employed in your study.
2. The diffuser pipeline and backbone models I've adopted might be ill-suited for this inpainting task.
3. The left image in the reference sheet, having a pure white background, may not provide adequate 3D cues for the backbone models. 

Do you have any other suggestions or recommendations worth trying, apart from these? Thank you! I plan on experimenting with an increased reference sheet size to see if improvements can be noted.

**Comment by JDihlmann** [comment]
Very cool, that you are interested and are working on something similar. First of all we discovered this effect also in a 2x1 grid so it should be possible, we only moved to a 2x3 grid to have less generations and more 3D consistent generations for multiple images. I just remembered that I indeed rebuild the pipeline with diffusers as we tried a self supervised Lora finetuning on the image grids to reach even more consistency (it failed but we also did not try it for long). I remember there were some tricks to get the diffusers pipeline working similar to the WebUI version (I invited you to the repository but beware that it is not documented and pure chaos). Also we discovered that the Controlnet Scale and Denoising Strength need to be within a certain range in order to have a successful generation (look at the values in our paper appendix). Also important is the sampler we only had successful generations with Euler A (this might be the problem in your case as from the results you are describing). In any case I would download SD WebUI and experiment there to see if you could find the right values and then transition back to diffusers again.

**Comment by Yzhbuaa** [comment]
Here is the result of the generation. Interestingly, another significant observation is that should I alter the background color to black, the generated view tends to assume a darker, more blackened appearance:
![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/1ec59904-cfd5-44f2-b46a-120f41b95549)

**Comment by Yzhbuaa** [comment]
Hey, good news, I just test [ControlNetInpaint](https://github.com/mikonvergence/ControlNetInpaint), and it works:
![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/1a9494fc-4328-4a29-bfb2-75ea02188a9f)

**Comment by JDihlmann** [comment]
Nice, I think you could achieve the same or better results with diffusers and SDXL! There must be something off with your current implementation.

**Comment by Yzhbuaa** [comment]
Absolutely! I will proceed with debugging, and once again, thank you for your detailed clarification.

**Comment by JDihlmann** [comment]
Best of luck, closing this issue for now 😄

**Comment by Yzhbuaa** [comment]
Hello @JDihlmann, I've recently experimented with the stable-diffusion-webui and integrated it with sd-webui-controlnet. Below, I've shared the outcomes and the configurations I used. It seems there may be an issue with my settings because the results aren't turning out as expected.

![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/654491e7-6734-45ae-a33a-879c17082c30)

![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/322974c3-31bf-4a23-ad38-69cc7fac88f1)

![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/cbe68e3c-b18c-42d2-ac10-996baf72f5e2)

![image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/44434e6a-011c-47fb-9370-6924f6b27f84)

**Comment by Yzhbuaa** [comment]
Here are my inputs:
![reference_sheet_image](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/219119c5-7dc2-49c9-b543-9cdde9ad1de6)
![reference_sheet_mask](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/4e681d64-935a-4e37-8050-0436ddfc40ae)
![reference_sheet_depth](https://github.com/cgtuebingen/SIGNeRF/assets/44798666/5cafb502-1ff9-4c87-bb8f-31bb91b64d7e)

**Comment by JDihlmann** [comment]
So I played a bit with your maps, I got it to work slightly but its not working perfectly. I think a big issue is that there is no content for the network ... I only got results when choosing masked content latent noise. Maybe copy your object over to the other side or place them closer to each other. Also be carfeful how you resize the image. Interesting that it works better with SD 1.5
