### ISSUE TITLE
Reference coordinate system

### ISSUE THREAD

**Issue by snowwhitewings** [cgtuebingen/SIGNeRF#8]
Hello, is the reference coordinate system that generates the position information when placing the proxy model object consistent with the reference coordinate system of the "camera_to_world" matrix generated during rendering? If not, what is the relationship between the two coordinate systems? 
Thank you for your reply.

**Comment by JDihlmann** [comment]
Hey, first as a general information: We are not changing anything about the data and coordinate conventions nerfstudio uses, so I would like to point to their [documentation](https://docs.nerf.studio/quickstart/data_conventions.html). The orientation of the coordinate system of the viser viewer and the nerfstudio internals should be identical. However, there is a scaling difference nerfstudio_pos * 10 => viser_pos and viser_pos / 10 => nerfstudio_pos. We handle this for you in our _signerf/interface/interface.py_ with the `VISER_NERFSTUDIO_SCALE_RATIO`. Just as an information.  

To answer your question for rendering the proxy object we use pyrenderer which has a different convention, see [here](https://pyrender.readthedocs.io/en/latest/examples/cameras.html). We indeed need to transfrom the "camera_to_world" matrix to fit within the setting of pyrender. I would like to refer to our _signerf/renderer/render.py_ script which has `render_camera` and more specifically `convert_matrix_to_pyrender` functions to explicitly handle this (<-- this is what you are looking for). Again also be careful here as we are scaling the scene in the setup with `NERFSTUDIO_BLENDER_SCALE_RATIO` to fit the Blender convention. 

Maybe also helpful if you export a OBJ model from Blender here are the settings we use to align with the Nerfstudio coordinate system: 
<img width="240" alt="Object Export Settings OBJ" src="https://github.com/cgtuebingen/SIGNeRF/assets/9963865/0f25877d-7d96-4e6a-9bd4-0299faf4e9c3">
