### ISSUE TITLE
How to get correct edited image

### ISSUE THREAD

**Issue by Jcx12138** [cgtuebingen/SIGNeRF#9]
Hello, thank you for your outstanding work and for making it open source. I'm currently experiencing some difficulties. When I use preview generation, I get wrong edited image. I haven't adjusted anything other than the reference camera and AABB, and the prompt is "a grizzly bear". Could you please give me some advice? Thank you for your reply :)
![M4O)%T{`@5~8G6 QXSSKTTT](https://github.com/cgtuebingen/SIGNeRF/assets/53679810/3f90b27b-ec1a-4b42-9ccc-167acef011cd)

**Comment by JDihlmann** [comment]
Hey, this looks indeed not right. However I cannot spot a direct error as the other maps all look good and also your input in the generation options. Maybe try a different seed and see if this error persists. However if it does not change, make sure you have the same version of SDXL and ControlNet as listed in the documentation. If so could you send me a screenshot of your terminal output from the SD WebUI after running the preview. For me it seems like it is ignoring ControlNet, this could be do the case of having a different ControlNet version and not specifying it in the SIGNeRF config as mentioned in the documentation.

**Comment by Jcx12138** [comment]
> Hey, this looks indeed not right. However I cannot spot a direct error as the other maps all look good and also your input in the generation options. Maybe try a different seed and see if this error persists. However if it does not change, make sure you have the same version of SDXL and ControlNet as listed in the documentation. If so could you send me a screenshot of your terminal output from the SD WebUI after running the preview. For me it seems like it is ignoring ControlNet, this could be do the case of having a different ControlNet version and not specifying it in the SIGNeRF config as mentioned in the documentation.

Thank you for your reminder. I rechecked the versions of Stable Diffusion and ControlNet, and now I can generate the correct images. However, this brings me some confusion: why did the new ControlNet version fail? Nevertheless, thanks again for your prompt response:D![image](https://github.com/cgtuebingen/SIGNeRF/assets/53679810/ee0449ec-8d21-456a-a57b-1cc01bd5b7b8)

**Comment by JDihlmann** [comment]
Ah perfect! It is not the ControlNet version that is incompatible with SIGNeRF it is an error within the communication of SD Web UI API. I don't know why they specified it like this but in order to tell the API to use ControlNet you have to send them the precise model `self.controlnet_model = diffusers_xl_depth_full [2f51180b]` with its commit hash.

```
"alwayson_scripts": {
                "controlnet": {
                    "args": [
                        {
                            "input_image": condition_image_bytes,
                            "model": self.controlnet_model,
                            "module": "none",
                            "weight": self.controlnet_conditioning_scale,
                            "guidance_start": self.controlnet_conditioning_scale_start,
                            "guidance_end": self.controlnet_conditioning_scale_end,
                            "lowvram": self.controlnet_lowvram,
                            "control_mode": self.controlnet_control_mode
                        }
                    ]
                }
            }
```

Since Nerfstudio does not know the current version of your SD Web UI ControlNet, you have to manually set it within the `signerf_config.py` (default our version). So you could use the new version but then need to set the version in the config. As far as I know you can't use the API without specifying the precise model name. But I'm glad that it works now have fun experimenting!

**Comment by Jcx12138** [comment]
> Ah perfect! It is not the ControlNet version that is incompatible with SIGNeRF it is an error within the communication of SD Web UI API. I don't know why they specified it like this but in order to tell the API to use ControlNet you have to send them the precise model `self.controlnet_model = diffusers_xl_depth_full [2f51180b]` with its commit hash.
> 
> ```
> "alwayson_scripts": {
>                 "controlnet": {
>                     "args": [
>                         {
>                             "input_image": condition_image_bytes,
>                             "model": self.controlnet_model,
>                             "module": "none",
>                             "weight": self.controlnet_conditioning_scale,
>                             "guidance_start": self.controlnet_conditioning_scale_start,
>                             "guidance_end": self.controlnet_conditioning_scale_end,
>                             "lowvram": self.controlnet_lowvram,
>                             "control_mode": self.controlnet_control_mode
>                         }
>                     ]
>                 }
>             }
> ```
> 
> Since Nerfstudio does not know the current version of your SD Web UI ControlNet, you have to manually set it within the `signerf_config.py` (default our version). So you could use the new version but then need to set the version in the config. As far as I know you can't use the API without specifying the precise model name. But I'm glad that it works now have fun experimenting!

I see. This is indeed my first time using Stable Diffusion. Thank you for your help. Wish you all the best with your work!
